name: Check Formatting

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download sqformat
        run: |
          curl -sSL https://github.com/Bobbyperson/sqformat/releases/download/v1.2.1/sqformat-linux-x86_64 -o sqformat
          chmod +x sqformat
      - name: Check formatting
        run: ./sqformat -dr .