name: Post-to-Mastodon
on:
  release:
    types: [ published ]

env:
  NORTHSTAR_VERSION: ${{ github.ref_name }}

jobs:
  build-northstar:
    runs-on: ubuntu-22.04
    steps:
        - name: Send toot to Mastodon
          id: mastodon
          uses: cbrgm/mastodon-github-action@v1
          with:
            message: "We just released a new Northstar version: ${{github.event.release.tag_name}}"
          env:
            MASTODON_URL: ${{ secrets.MASTODON_URL }}
            MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
