name: Release
on:
  push:
  workflow_dispatch:

permissions:
  contents: write # Needed to write to GitHub draft release

env:
  NORTHSTAR_VERSION: ${{ github.ref_name }}
  DISCORD_RPC_VERSION: v14

jobs:
  build-northstar:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-substituters = https://attic.catornot.net/northstar https://nix-community.cachix.org
            extra-trusted-public-keys = northstar:H8QBUAeduEw6jGl3HtGeW/79pMPv7wSCAv8BSUon3kw= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Build
        run: |
          nix build 

      - name: Get Northstar version
        run: |
          echo "NORTHSTAR_VERSION=$(nix eval --raw .#version)" >> "$GITHUB_ENV"

      - name: Upload
        uses: actions/upload-artifact@v5
        with:
          name: Northstar.release.${{ env.NORTHSTAR_VERSION }}
          path: ./result

      - name: Create zip to upload
        run: |
          zip --recurse-paths --quiet Northstar.release.${{ env.NORTHSTAR_VERSION }}.zip ./result

      - name: Compute SHA-512 checksum
        run: |
          sha512sum Northstar.release.${{ env.NORTHSTAR_VERSION }}.zip
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          sha512sum Northstar.release.${{ env.NORTHSTAR_VERSION }}.zip >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Upload zip to release draft
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v') && !contains(env.NORTHSTAR_VERSION, '-rc')
        with:
          draft: true
          files: Northstar.release.${{ env.NORTHSTAR_VERSION }}.zip
